#!/usr/bin/env python

# -*- coding: utf-8 -*-
"""
Created on Wed Apr 24 11:18:19 2013

@author: edouard.duchesnay@cea.fr
@author: benoit.da_mota@inria.fr
@author: jinpeng.li@cea.fr
"""

import sys
import os

if __name__ == "__main__":
    print os.getcwd()
    filename = sys.argv[1]
    fin = open(filename, "rb")
    key_lines = fin.readlines()
    print key_lines
    fin.close()
